# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo')),
                ('info', models.CharField(max_length=500, verbose_name='Informaci\xf3n')),
                ('link', models.CharField(max_length=500, verbose_name='Liga')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de publicaci\xf3n')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('details', models.CharField(max_length=500, verbose_name='Detalles')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de publicaci\xf3n')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugar',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo')),
                ('info', models.CharField(max_length=500, verbose_name='Informaci\xf3n')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de publicaci\xf3n')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_by_locations', to='services.Location', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_by_type', to='services.Type', verbose_name='Tipo'),
        ),
    ]
